// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5X6e1Ay6zaAqR51YhXHx2FobPaAGO_A',
    appId: '1:886608987793:web:b00a729f866c759be72130',
    messagingSenderId: '886608987793',
    projectId: 'glucolife-d4f1e',
    authDomain: 'glucolife-d4f1e.firebaseapp.com',
    storageBucket: 'glucolife-d4f1e.appspot.com',
    measurementId: 'G-E4RSQ7VPS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAkZqEGnbhZQIrVhFxMqR29UcLxpP4ACY',
    appId: '1:886608987793:android:4f47e1a215752837e72130',
    messagingSenderId: '886608987793',
    projectId: 'glucolife-d4f1e',
    storageBucket: 'glucolife-d4f1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCijEbAn6FE4TxjBm7W2BbeW1MMetlb9Mg',
    appId: '1:886608987793:ios:1465e0106463ee16e72130',
    messagingSenderId: '886608987793',
    projectId: 'glucolife-d4f1e',
    storageBucket: 'glucolife-d4f1e.appspot.com',
    iosBundleId: 'com.example.glucolifeProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCijEbAn6FE4TxjBm7W2BbeW1MMetlb9Mg',
    appId: '1:886608987793:ios:84a3b4af2ac29f72e72130',
    messagingSenderId: '886608987793',
    projectId: 'glucolife-d4f1e',
    storageBucket: 'glucolife-d4f1e.appspot.com',
    iosBundleId: 'com.example.glucolifeProyecto.RunnerTests',
  );
}
